name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-api:
    name: Deploy api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile
      - run: auto/deploy-api

  deploy-ui:
    name: Deploy ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile
      - run: auto/build-ui
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/ui
